let range = document.querySelectorAll(".a02")
console.log(range)

let simimage = document.querySelectorAll(".simimage")
let imagearea = document.querySelector("#b0")
let textarea = document.querySelector("#b1")
range[0].addEventListener("click",function(){
    textarea.innerText = `Range Rover is a luxury SUV brand known for its combination of off-road capability and opulent comfort. The brand is owned by Tata Motors through Land Rover and offers models like the larger Range Rover and the sportier Range Rover Sport. Features include powerful engine options (including mild hybrid, petrol, and diesel), advanced all-wheel steering, advanced infotainment systems like Pivi Pro, and air suspension for a smooth ride. Brand and ownership  The Range Rover brand is part of Land Rover, which is owned by the Indian auto manufacturer Tata Motors.The brand has a long history, with the first model being launched in 1970. Key models and features
Range Rover: The flagship model is a large, luxurious SUV with seating for up to seven people. It is known for its comfortable ride and off-road capability, offering a choice of engines, including mild-hybrid options and a powerful V8.
Range Rover Sport: This model is a sportier, more performance-oriented SUV. It is available in various engine configurations, including a high-performance Supercharged V8 in the SVR variant. Performance and technology
Engines: Models are available with efficient mild hybrid petrol and diesel engines, as well as more powerful options, like a 4.4-liter V8.
Capability: The brand uses advanced systems like permanent 4-wheel drive and air suspension to provide off-road capability and a comfortable on-road experience.
Technology: Modern features include a Pivi Pro infotainment system with a large, curved display, 3D surround cameras, and an all-wheel steering system for enhanced agility.
Hybrid options: Extended-range plug-in hybrid models are available, which can provide an electric-only range of up to 100 km on the WLTP cycle.  Pricing and availability
Prices vary significantly based on the model and trim level, with the Range Rover starting around ₹ 1.66 Crore (ex-showroom) and the Range Rover Sport starting around ₹ 1.38 Crore (ex-showroom) in India, as of late 2022.
The luxury-focused Range Rover Autobiography by SVO Bespoke has a higher starting price.
The high-performance Range Rover Sport SVR has a starting price of around ₹ 2.19 Crore (ex-showroom). `
 simimage[0].setAttribute("src","https://cdn.motor1.com/images/mgl/mMP1PB/s1/2023-range-rover-velar.jpg")
 simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf1w9voFFnhgTb44f09OkUtcmHxq0MqFstew&s")

})

range[1].addEventListener("click",function(){
 textarea.innerText = "The Land Rover Defender (introduced as the Land Rover One Ten, joined in 1984 by the Land Rover Ninety, plus the extra-length Land Rover One Two Seven in 1985) is a series of British off-road cars and pickup trucks. They have four-wheel drive, and were developed in the 1980s from the Land Rover series which was launched at the Amsterdam Motor Show in April 1948.Following the 1989 introduction of the Land Rover Discovery, the term 'Land Rover' became the name of a broader marque, no longer the name of a specific model; thus in 1990 Land Rover renamed them as Defender 90 and Defender 110 and Defender 130 respectively.The vehicle, a British equivalent of the Second World War derived (Willys) Jeep, gained a worldwide reputation for ruggedness and versatility. With a steel ladder chassis and an aluminium alloy bodywork, the Land Rover originally used detuned versions of Rover engines.Though the Defender was not a new generation design, it incorporated significant changes compared to the Land Rover series, such as adopting coil springs front and rear. Coil springs offered both better ride quality and improved axle articulation. The addition of a centre differential to the transfer case gave the Defender permanent four-wheel-drive capability. Both changes were derived from the original Range Rover, and the interiors were also modernised. Whilst the engines were carried over from the Series III, a new series of modern and more powerful engines was progressively introduced.Even when ignoring the series Land Rovers and perhaps ongoing licence products, the 90/110 and Defender models' 33-year production run were ranked as the sixteenth longest single-generation car in history in 2020.In 2020, Jaguar Land Rover introduced an all new generation of Land Rover Defender Land Rover Defender (L663) switching from body on chassis to integrated bodywork and from live, rigid axles to all around independent suspension.A special edition Defender Works V8, with 400 bhp (298 kW), was announced in January 2018.[7] Until 2020, the Defender was last sold in North America in 1997 due to low sales and modifications required to comply with updated safety standards.An all-new 2020 Land Rover Defender made its global debut in September 2019 and was initially offered with two wheelbase options. This new model, which shares no components or technology with its predecessor, has an aluminium monocoque body"
 img = simimage[0].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_pYSdQe9gmj3thytFf5KgyEBNggpT1SATw&s")
 img1 = simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjxWs2gSduBLOI7fOFQ01QI7ieAbJWf6e_w&s")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","280px")
})
range[2].addEventListener("click",function(){
    textarea.innerText = "lorem"
    textarea.innerText = "The Land Rover Defender (introduced as the Land Rover One Ten, joined in 1984 by the Land Rover Ninety, plus the extra-length Land Rover One Two Seven in 1985) is a series of British off-road cars and pickup trucks. They have four-wheel drive, and were developed in the 1980s from the Land Rover series which was launched at the Amsterdam Motor Show in April 1948.Following the 1989 introduction of the Land Rover Discovery, the term 'Land Rover' became the name of a broader marque, no longer the name of a specific model; thus in 1990 Land Rover renamed them as Defender 90 and Defender 110 and Defender 130 respectively.The vehicle, a British equivalent of the Second World War derived (Willys) Jeep, gained a worldwide reputation for ruggedness and versatility. With a steel ladder chassis and an aluminium alloy bodywork, the Land Rover originally used detuned versions of Rover engines.Though the Defender was not a new generation design, it incorporated significant changes compared to the Land Rover series, such as adopting coil springs front and rear. Coil springs offered both better ride quality and improved axle articulation. The addition of a centre differential to the transfer case gave the Defender permanent four-wheel-drive capability. Both changes were derived from the original Range Rover, and the interiors were also modernised. Whilst the engines were carried over from the Series III, a new series of modern and more powerful engines was progressively introduced.Even when ignoring the series Land Rovers and perhaps ongoing licence products, the 90/110 and Defender models' 33-year production run were ranked as the sixteenth longest single-generation car in history in 2020.In 2020, Jaguar Land Rover introduced an all new generation of Land Rover Defender Land Rover Defender (L663) switching from body on chassis to integrated bodywork and from live, rigid axles to all around independent suspension.A special edition Defender Works V8, with 400 bhp (298 kW), was announced in January 2018.[7] Until 2020, the Defender was last sold in North America in 1997 due to low sales and modifications required to comply with updated safety standards.An all-new 2020 Land Rover Defender made its global debut in September 2019 and was initially offered with two wheelbase options. This new model, which shares no components or technology with its predecessor, has an aluminium monocoque body"
 img = simimage[0].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_pYSdQe9gmj3thytFf5KgyEBNggpT1SATw&s")
 img1 = simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjxWs2gSduBLOI7fOFQ01QI7ieAbJWf6e_w&s")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","200px")
})
range[3].addEventListener("click",function(){
    textarea.innerText = "lorem"
    textarea.innerText = "The Land Rover Defender (introduced as the Land Rover One Ten, joined in 1984 by the Land Rover Ninety, plus the extra-length Land Rover One Two Seven in 1985) is a series of British off-road cars and pickup trucks. They have four-wheel drive, and were developed in the 1980s from the Land Rover series which was launched at the Amsterdam Motor Show in April 1948.Following the 1989 introduction of the Land Rover Discovery, the term 'Land Rover' became the name of a broader marque, no longer the name of a specific model; thus in 1990 Land Rover renamed them as Defender 90 and Defender 110 and Defender 130 respectively.The vehicle, a British equivalent of the Second World War derived (Willys) Jeep, gained a worldwide reputation for ruggedness and versatility. With a steel ladder chassis and an aluminium alloy bodywork, the Land Rover originally used detuned versions of Rover engines.Though the Defender was not a new generation design, it incorporated significant changes compared to the Land Rover series, such as adopting coil springs front and rear. Coil springs offered both better ride quality and improved axle articulation. The addition of a centre differential to the transfer case gave the Defender permanent four-wheel-drive capability. Both changes were derived from the original Range Rover, and the interiors were also modernised. Whilst the engines were carried over from the Series III, a new series of modern and more powerful engines was progressively introduced.Even when ignoring the series Land Rovers and perhaps ongoing licence products, the 90/110 and Defender models' 33-year production run were ranked as the sixteenth longest single-generation car in history in 2020.In 2020, Jaguar Land Rover introduced an all new generation of Land Rover Defender Land Rover Defender (L663) switching from body on chassis to integrated bodywork and from live, rigid axles to all around independent suspension.A special edition Defender Works V8, with 400 bhp (298 kW), was announced in January 2018.[7] Until 2020, the Defender was last sold in North America in 1997 due to low sales and modifications required to comply with updated safety standards.An all-new 2020 Land Rover Defender made its global debut in September 2019 and was initially offered with two wheelbase options. This new model, which shares no components or technology with its predecessor, has an aluminium monocoque body"
 img = simimage[0].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_pYSdQe9gmj3thytFf5KgyEBNggpT1SATw&s")
 img1 = simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjxWs2gSduBLOI7fOFQ01QI7ieAbJWf6e_w&s")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","180px")
})
range[4].addEventListener("click",function(){
    textarea.innerText = "lorem"
    textarea.innerText = "The Land Rover Defender (introduced as the Land Rover One Ten, joined in 1984 by the Land Rover Ninety, plus the extra-length Land Rover One Two Seven in 1985) is a series of British off-road cars and pickup trucks. They have four-wheel drive, and were developed in the 1980s from the Land Rover series which was launched at the Amsterdam Motor Show in April 1948.Following the 1989 introduction of the Land Rover Discovery, the term 'Land Rover' became the name of a broader marque, no longer the name of a specific model; thus in 1990 Land Rover renamed them as Defender 90 and Defender 110 and Defender 130 respectively.The vehicle, a British equivalent of the Second World War derived (Willys) Jeep, gained a worldwide reputation for ruggedness and versatility. With a steel ladder chassis and an aluminium alloy bodywork, the Land Rover originally used detuned versions of Rover engines.Though the Defender was not a new generation design, it incorporated significant changes compared to the Land Rover series, such as adopting coil springs front and rear. Coil springs offered both better ride quality and improved axle articulation. The addition of a centre differential to the transfer case gave the Defender permanent four-wheel-drive capability. Both changes were derived from the original Range Rover, and the interiors were also modernised. Whilst the engines were carried over from the Series III, a new series of modern and more powerful engines was progressively introduced.Even when ignoring the series Land Rovers and perhaps ongoing licence products, the 90/110 and Defender models' 33-year production run were ranked as the sixteenth longest single-generation car in history in 2020.In 2020, Jaguar Land Rover introduced an all new generation of Land Rover Defender Land Rover Defender (L663) switching from body on chassis to integrated bodywork and from live, rigid axles to all around independent suspension.A special edition Defender Works V8, with 400 bhp (298 kW), was announced in January 2018.[7] Until 2020, the Defender was last sold in North America in 1997 due to low sales and modifications required to comply with updated safety standards.An all-new 2020 Land Rover Defender made its global debut in September 2019 and was initially offered with two wheelbase options. This new model, which shares no components or technology with its predecessor, has an aluminium monocoque body"
 img = simimage[0].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_pYSdQe9gmj3thytFf5KgyEBNggpT1SATw&s")
 img1 = simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjxWs2gSduBLOI7fOFQ01QI7ieAbJWf6e_w&s")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","180px")
})