let range = document.querySelectorAll(".a02")
console.log(range)

let simimage = document.querySelectorAll(".simimage")
let imagearea = document.querySelector("#b0")
let textarea = document.querySelector("#b1")
range[0].addEventListener("click",function(){
    textarea.innerText = `Range Rover is a luxury SUV brand known for its combination of off-road capability and opulent comfort. The brand is owned by Tata Motors through Land Rover and offers models like the larger Range Rover and the sportier Range Rover Sport. Features include powerful engine options (including mild hybrid, petrol, and diesel), advanced all-wheel steering, advanced infotainment systems like Pivi Pro, and air suspension for a smooth ride. Brand and ownership  The Range Rover brand is part of Land Rover, which is owned by the Indian auto manufacturer Tata Motors.The brand has a long history, with the first model being launched in 1970. Key models and features
Range Rover: The flagship model is a large, luxurious SUV with seating for up to seven people. It is known for its comfortable ride and off-road capability, offering a choice of engines, including mild-hybrid options and a powerful V8.
Range Rover Sport: This model is a sportier, more performance-oriented SUV. It is available in various engine configurations, including a high-performance Supercharged V8 in the SVR variant. Performance and technology
Engines: Models are available with efficient mild hybrid petrol and diesel engines, as well as more powerful options, like a 4.4-liter V8.
Capability: The brand uses advanced systems like permanent 4-wheel drive and air suspension to provide off-road capability and a comfortable on-road experience.
Technology: Modern features include a Pivi Pro infotainment system with a large, curved display, 3D surround cameras, and an all-wheel steering system for enhanced agility.
Hybrid options: Extended-range plug-in hybrid models are available, which can provide an electric-only range of up to 100 km on the WLTP cycle.  Pricing and availability
Prices vary significantly based on the model and trim level, with the Range Rover starting around ₹ 1.66 Crore (ex-showroom) and the Range Rover Sport starting around ₹ 1.38 Crore (ex-showroom) in India, as of late 2022.
The luxury-focused Range Rover Autobiography by SVO Bespoke has a higher starting price.
The high-performance Range Rover Sport SVR has a starting price of around ₹ 2.19 Crore (ex-showroom). `
 simimage[0].setAttribute("src","https://cdn.motor1.com/images/mgl/mMP1PB/s1/2023-range-rover-velar.jpg")
 simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRf1w9voFFnhgTb44f09OkUtcmHxq0MqFstew&s")

})

range[1].addEventListener("click",function(){
 textarea.innerText = "The Land Rover Defender (introduced as the Land Rover One Ten, joined in 1984 by the Land Rover Ninety, plus the extra-length Land Rover One Two Seven in 1985) is a series of British off-road cars and pickup trucks. They have four-wheel drive, and were developed in the 1980s from the Land Rover series which was launched at the Amsterdam Motor Show in April 1948.Following the 1989 introduction of the Land Rover Discovery, the term 'Land Rover' became the name of a broader marque, no longer the name of a specific model; thus in 1990 Land Rover renamed them as Defender 90 and Defender 110 and Defender 130 respectively.The vehicle, a British equivalent of the Second World War derived (Willys) Jeep, gained a worldwide reputation for ruggedness and versatility. With a steel ladder chassis and an aluminium alloy bodywork, the Land Rover originally used detuned versions of Rover engines.Though the Defender was not a new generation design, it incorporated significant changes compared to the Land Rover series, such as adopting coil springs front and rear. Coil springs offered both better ride quality and improved axle articulation. The addition of a centre differential to the transfer case gave the Defender permanent four-wheel-drive capability. Both changes were derived from the original Range Rover, and the interiors were also modernised. Whilst the engines were carried over from the Series III, a new series of modern and more powerful engines was progressively introduced.Even when ignoring the series Land Rovers and perhaps ongoing licence products, the 90/110 and Defender models' 33-year production run were ranked as the sixteenth longest single-generation car in history in 2020.In 2020, Jaguar Land Rover introduced an all new generation of Land Rover Defender Land Rover Defender (L663) switching from body on chassis to integrated bodywork and from live, rigid axles to all around independent suspension.A special edition Defender Works V8, with 400 bhp (298 kW), was announced in January 2018.[7] Until 2020, the Defender was last sold in North America in 1997 due to low sales and modifications required to comply with updated safety standards.An all-new 2020 Land Rover Defender made its global debut in September 2019 and was initially offered with two wheelbase options. This new model, which shares no components or technology with its predecessor, has an aluminium monocoque body"
 img = simimage[0].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_pYSdQe9gmj3thytFf5KgyEBNggpT1SATw&s")
 img1 = simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjxWs2gSduBLOI7fOFQ01QI7ieAbJWf6e_w&s")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","280px")
})
range[2].addEventListener("click",function(){
    textarea.innerText = "lorem"
 img = simimage[0].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRX_pYSdQe9gmj3thytFf5KgyEBNggpT1SATw&s")
 img1 = simimage[1].setAttribute("src","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEjxWs2gSduBLOI7fOFQ01QI7ieAbJWf6e_w&s")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","200px")
})
range[3].addEventListener("click",function(){
    textarea.innerText = "The Mercedes-Benz Group's marques are Mercedes-Benz for cars and vans (including Mercedes-AMG and Mercedes-Maybach). It has shares in other vehicle manufacturers such as Daimler Truck, BAIC Motor and Aston Martin. Since 2019, Smart left Daimler AG and became a 50/50 joint venture with Geely.The Mercedes-Benz Group's marques are Mercedes-Benz for cars and vans (including Mercedes-AMG and Mercedes-Maybach). It has shares in other vehicle manufacturers such as Daimler Truck, BAIC Motor and Aston Martin. Since 2019, Smart left Daimler AG and became a 50/50 joint venture with Geely.In a so-called according to its then CEO and architect Jürgen E. Schrempp,[13] Daimler-Benz, and United States–based automobile manufacturer Chrysler Corporation, the smallest of the main three American automakers, merged in 1998 in an exchange of shares[14] and formed DaimlerChrysler AG. Valued at US$38 billion, it was the world's largest ever cross-border deal.[15]The merger was contentious with investors launching lawsuits over whether the transaction was the 'merger of equals' that senior management claimed or actually amounted to a Daimler-Benz takeover of Chrysler. A class action investor lawsuit was settled in August 2003 for US$300 million while a suit by billionaire investor activist Kirk Kerkorian was dismissed on 7 April 2005.[17] The transaction claimed the job of its architect, Chairman Jürgen E. Schrempp, who resigned at the end of 2005 in response to the fall of the company's share price following the transaction.Another issue of contention is whether the merger delivered promised synergies and successfully integrated the two businesses. Martin H. Wiggers' concept of a platform strategy, like the VW Group's, was implemented only for a few models, so the synergy effects in development and production were low.[19] As late as 2002, DaimlerChrysler appeared to run two independent product lines. Later that year, the company launched products that did integrate elements from both sides of the company, including the Chrysler Crossfire, which was based on the Mercedes SLK platform and utilized Mercedes's 3.2 L V6, and the Dodge Sprinter/Freightliner Sprinter, a re-badged Mercedes-Benz Sprinter van."
 img = simimage[0].setAttribute("src","")
 img1 = simimage[1].setAttribute("src","")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","180px")
})
range[4].addEventListener("click",function(){

    textarea.innerText = "The Škoda Octavia is a small family car (C-segment) produced by the Czech car manufacturer Škoda Auto since the end of 1996. It shares its name with an earlier model produced between 1959 and 1971. Four generations of the modern-era Octavia model have been introduced to date, delivered with five-door liftback or five-door estate styles only. The car is front engined and both front- or four-wheel drive are offered. Around five million units have been sold in its two decades of presence on the market.[1] The Octavia is Škoda's most popular model; about 40% of all newly manufactured Škoda cars are Octavias.The current generation is available in a wide range of derivatives, i.e. sporty Octavia RS, estate Octavia Combi, four-wheel drive Octavia Scout, frugal Octavia GreenLine and CNG-powered OctaviaVauxhall Motors, the British GM subsidiary that shared most of its models with Opel, did not use the  model name - opting instead to continue the use of the Cavalier nameplate - effectively making the Vectra A a third-generation Cavalier when carrying Vauxhall branding. It was not until the introduction of the Vectra B into the United Kingdom in October 1995 that the Cavalier name was retired in favour of Vectra. However, left hand drive Opel Vectras were produced at Vauxhall's Luton plant for export to other European countries.[5]The 1989 Vectra came in Base, LS, GL, GLS, CD, and GT models, its sister model was the third-generation Cavalier. Engines ranged initially from a 75 PS (55 kW) 1.4 L to a 130 PS (96 kW) 2.0 L Family II. The top-of-the-line Vectra 2000 16V arrived in September 1989. Its sixteen valve version of the 2.0 L engine produces 150 PS (110 kW) and was only available with the sedan bodywork, with available four-wheel drive.The sixteen-valve engine also appeared in GT (GSi in some markets) models after the facelift, now mainly as a hatchback. Two four-wheel drive versions were added to the lineup in January 1989, with either of the 2-litre engines, and in September 1992 the car received a limited edition turbocharged version with 204 PS (150 kW). In 1994, the 4x4 turbo version of the Vectra was used as the Safety Car in Formula One, where it was deployed at the San Marino Grand Prix."
 img = simimage[0].setAttribute("src","https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Opel_Vectra_C_2.2_Direkt_front.JPG/500px-Opel_Vectra_C_2.2_Direkt_front.JPG")
 img1 = simimage[1].setAttribute("src","https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Opel_Vectra_%2813033887374%29_%282%29.jpg/500px-Opel_Vectra_%2813033887374%29_%282%29.jpg")
 img3 = simimage[0].setAttribure("height","250px")
 img2 = simimage[1].setAttribute("height","180px")
})